In [1]:
import numpy as np


In [3]:
arr =np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr=np.array((1,2,3,4,5))
print (arr)

[1 2 3 4 5]


 Dimension in array

In [5]:
arr=np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


#1D array

In [6]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


#2D array

In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
arr=np.array([[1.1,2,3.4],[4.4,5,6.6]])
print(arr)
print(arr.ndim)

[[1.1 2.  3.4]
 [4.4 5.  6.6]]
2


#3D array

In [13]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])

print(arr)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 5 6]]]
3


#All dimension

In [19]:
a=np.array(23)
b=np.array([1,2,3,4])
c=np.array([[1,2,3],[2,3,4]])
d=np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Create a 5 dimension array and verify that it has 5 dimension

In [25]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("Number of dimension:",arr.ndim)

[[[[[[1 2 3 4 5]]]]]]
Number of dimension: 6


In [ ]:
arr=np.array([1,2,3,4,5],ndmin=1)
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


Numpy array indexing:

   
Get the first elemetn of array


In [30]:
arr=np.array([1,2,3,4,5])
print(arr[0])


1


Get third and eight element of an array and add them

In [34]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print('third element:',arr[2])
print('8th element is:',arr[7])
print('sum of element is:',arr[2]+arr[7])

third element: 3
8th element is: 8
sum of element is: 11


Get indexing of 2D array

In [38]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print("2nd element of 1st row :",arr[0,1])
print(arr)

2nd element of 1st row : 2
[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('3rd element of 1st row :',arr[0,2])

3rd element of 1st row : 3


#add first element and last element of  2d array

In [8]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print('1st element of 1st row :',arr[0,0])
print('last element of 2nd row : ',arr[-1,-1])
print('sum of first and last element is :',arr[0,0]+arr[-1,-1])

1st element of 1st row : 1
last element of 2nd row :  8
sum of first and last element is : 9


#Access 3D array

In [12]:
arr=np.array([[[1,23,4],[1,2,4]],[[5,6,78],[9,8,7]]])
print(arr)
print(arr.ndim)
print(arr[0,0,1])

[[[ 1 23  4]
  [ 1  2  4]]

 [[ 5  6 78]
  [ 9  8  7]]]
3
23
