Slicing in Array numpy

In [1]:
import numpy as np


In [6]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:5:2])
print(arr[::2])

[2 4]
[1 3 5]


Slicing in 2D array

In [9]:
arr=np.array([[1,2,3,4],[4,3,2,1]])
print(arr[1,1:4])

[3 2 1]


In [10]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,0:3])

[10 20 30]


Checking the data type of array

In [12]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [13]:
arr=np.array(['animal','cat','dog'])
print(arr.dtype)

<U6


Creating array with a defined data types

In [17]:
arr=np.array([2,3,4,5,6],dtype= 'S')
print(arr)
print(arr.dtype)

[b'2' b'3' b'4' b'5' b'6']
|S1


Create an array with data type 4bytes integer

In [20]:
a=np.array([1,2,3,4],dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4]
int32


Numpy array Shape

the shape of an array the number of element in each dimension

print the shape of 2d array

In [21]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)


(2, 4)


3D array shape

In [23]:
a=np.array([[[1,2,3,4],[5,6,7,8],[9,8,7,6]]])
print(a)
print(a.shape)

[[[1 2 3 4]
  [5 6 7 8]
  [9 8 7 6]]]
(1, 3, 4)


Joining Numpy array

In [30]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,8,6,7])
arr=np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 8 6 7]


join 2D array

In [34]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[9,8,7],[6,5,4]])
arr=np.concatenate((arr1,arr2),axis=1) #rowise
print(arr)

[[1 2 3 9 8 7]
 [4 5 6 6 5 4]]


In [35]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[9,8,7],[6,5,4]])
arr=np.concatenate((arr1,arr2),axis=0) #columnwise
print(arr)

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 5 4]]


Splitting Numpy Array

Splitting the array in 3 part

In [38]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Ravel &flatten

convert mutidimension array into 1 d array

In [40]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimnesion of array:' ,m.ndim)
n=m.ravel()
print(n)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimnesion of array: 3
[1 2 3 4 5 6 7 8 9]


In [46]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('dimnesion of array:' ,m.ndim)
n=m.flatten()
print(n)
print("now new dimension :",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimnesion of array: 3
[1 2 3 4 5 6 7 8 9]
now new dimension : 1


In [47]:
c=np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(c)
print("dimension of array: ",c.ndim)
d=c.flatten()
print(d)
print("now new dimension :",d.ndim)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
dimension of array:  4
[1 2 3 4 5 6 7 8]
now new dimension : 1


#/unique Function

In [51]:
k=np.array([1,3,3,3,7,8,3,1,5,8,94,32,21,32,14,5,19])
print(k)
x=np.unique(k)
print(x)

[ 1  3  3  3  7  8  3  1  5  8 94 32 21 32 14  5 19]
[ 1  3  5  7  8 14 19 21 32 94]


In [52]:
k=np.array([1,3,3,3,7,8,3,1,5,8,94,32,21,32,14,5,19])
print(k)
x=np.unique(k,return_index=True)
print(x)

[ 1  3  3  3  7  8  3  1  5  8 94 32 21 32 14  5 19]
(array([ 1,  3,  5,  7,  8, 14, 19, 21, 32, 94]), array([ 0,  1,  8,  4,  5, 14, 16, 12, 11, 10]))


In [54]:
k=np.array([1,3,3,3,7,8,3,1,5,8,94,32,21,32,14,5,19])
print(k)
x=np.unique(k,return_index=True, return_counts=True)
print(x)

[ 1  3  3  3  7  8  3  1  5  8 94 32 21 32 14  5 19]
(array([ 1,  3,  5,  7,  8, 14, 19, 21, 32, 94]), array([ 0,  1,  8,  4,  5, 14, 16, 12, 11, 10]), array([2, 4, 2, 1, 2, 1, 1, 1, 2, 1]))


DELETE

In [55]:
a=np.array([1,2,3,5])
b=np.delete(a,[3])
print(a)
print(b)

[1 2 3 5]
[1 2 3]
